spring:
  application:
    name: smart-metrics-user
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yml
        namespace: metrics-default